name: 'deployment'
on:
    workflow_dispatch:
      inputs:
        stage:
          description: 'stage [local,dev,prod]'
          required: true
          default: 'local'
          type: choice
          options: 
            - local
            - dev
            - prod
        releasetype:
          description: 'select the release type'
          required: true
          type: choice
          options: 
            - major
            - minor
            - patch
jobs:
  deploy:
    environment: ${{ github.event.inputs.stage }}
    name: deployments
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
    steps:
      - uses: actions/checkout@v2

      - name: Fetch the last release tag
        run: |
          old-version=$(git describe --tags --abbrev=0 --match v*)
          chmod +x ./deployment/version-update.sh
          new-version="$(bash ./deployment/version-update.sh $old-version ${{ github.event.inputs.releasetype }} )" >> $GITHUB_ENV

      # S3 bucket is in AWS dev account  
      - name: Configure AWS for fetching S3 data and putting it back
        run: |
          aws configure set aws_access_key_id ${{ secrets.S3_POLICY_KEY}} --profile s3fetch
          aws configure set aws_secret_access_key ${{ secrets.S3_POLICY_SECRET }} --profile s3fetch

      - name: Create deployment package
        run: |
          chmod +x ./deployment/build-s3-dist.sh
          ./deployment/build-s3-dist.sh ${{ secrets.S3_BUCKET }} video-on-demand-on-aws ${{ env.new-version }}
      
      - name: Copy the content to the S3 bucket and make the object public.
        run: |
          aws s3 cp ./regional-s3-assets/ s3://${{ secrets.S3_BUCKET }}/video-on-demand-on-aws/${{ env.new-version }}/ --recursive --acl bucket-owner-full-control --profile s3fetch
          aws s3api put-object-acl --bucket ${{ secrets.S3_BUCKET }} --key video-on-demand-on-aws/${{ env.new-version }}/video-on-demand-on-aws.template --acl public-read --profile s3fetch

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: media-bucket-${{ github.event.inputs.stage }}
          template: https://s3.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.S3_BUCKET }}/video-on-demand-on-aws/${{ env.new-version }}/video-on-demand-on-aws.template
          parameter-overrides: "SourceBucketStack=content-bucket-${{ github.event.inputs.stage }},DestinationBucketStack=content-bucket-${{ github.event.inputs.stage }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.new-version }}
          release_name: ${{ env.new-version }}
